apache/skywalking-rocketbot-ui

- src/views/containers/alarm.vue
- src/views/containers/topology.vue
- src/views/containers/trace.vue
The flex items cannot shrink to proper height in Firefox.
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1043520
Unexpected behavior:
Fixed:
> Fix: add workaround about firefox flexbox bug

- src/store/modules/dashboard/template/endpoint-template.ts
- src/utils/queryChartData.ts
- src/views/components/dashboard/charts/chart-slow.vue
- src/views/components/dashboard/charts/chart-trace.vue
- vue.config.js
before:
Paste board content is label value
after:
Paste board content is traceIds[0] value
> fix-dashboard-endpoint-trace-incorrect

- src/views/components/trace/trace-search.vue
People want to use the trace URL parameters to visit the specified trace information instead of using Search button. It is very useful for some tools to use hyperlink to jump to skywalking trace page via endpointname and trace ID. This update is for URL parameters to visite specified trace.
example:
http://localhost:8880/trace?endpointname=runtest&traceid=2.30.15753618423830000
> Use URL parameters to visit specified trace

- src/event-bus.ts
- src/types/vue.d.ts
something about the commits:
- In *.vue files, `this.$evnentBus`  is `any` type.
- Vue.js plugin should expose an install method. The method will be called with the Vue constructor as the first argument.not Vue type. [check Vue documentation](https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin).but `EventBus.install` first argument is Vue type.
- the `private` method `$offVmEvent` is called from outside,
```ts
vue.mixin({
deactivated() {
// private method is called here
this.$eventBus.$offVmEvent(this._uid);
},
beforeDestroy() {
this.$eventBus.$offVmEvent(this._uid);
},
});
```
> update event-bus type

- src/store/modules/topology/index.ts
- src/store/mutation-types.ts
- src/views/components/topology/chart/topo.vue
- src/views/components/topology/topo-aside.vue
- src/views/containers/topology/topology.vue
Fixes https://github.com/apache/skywalking-rocketbot-ui/issues/279 . Refresh detect point data when we update calendar.
**screenshots**
> Fix: refresh detect point data

- .asf.yaml
Recently the PR and comments events are sent to the dev@ mailing list, which generates much noise, this patch creates `.asf.yaml` to mute the events and sends them to notifications@ ML for those who are interested in the events
> Create .asf.yaml to mute the noises from PR/comments

- .asf.yaml
According to the infra team, the indentations are wrong, which causes the notifications are still sent to the dev@ ML
> Fix wrong indentations in .asf.yaml

- src/views/components/common/trace-detail-chart-table.vue
- src/views/components/trace/d3-trace.js
- src/views/components/trace/trace-detail-chart-list.vue
- src/views/components/trace/trace-detail-chart-tree.vue
handle the situation with VNode
1、define the trace tree list‘s svg’s height depends on the fixSpansSize
2、avoid the VNode add child nodes for twice
related issues: resolves https://github.com/apache/skywalking/issues/5301
> handle the situation with VNode

- src/views/containers/topology/instance/index.vue
Refer to https://github.com/apache/skywalking-rocketbot-ui/issues/358. Fixes the current service for topology instance page.
Screenshot
signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>
> fix: Set current service for topology

- package-lock.json
- package.json
https://sass-lang.com/dart-sass
> Dart Sass is the primary implementation of Sass, which means it gets new features before any other implementation. It's fast, easy to install, and it compiles to pure JavaScript which makes it easy to integrate into modern web development workflows. Find out more or help out with its development on GitHub.
https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0
> prefer sass (dart-sass) by default, it is strongly recommended to migrate on sass (dart-sass)
> feat: remove node-sass, use dart-sass

- src/views/components/topology/radial.vue
A small fix/tweak. I'm assuming, that "Service" is a valid label in this place.
> Removed "Les Miserables" from radial chart in topology.

- src/store/modules/dashboard/dashboard-option.ts
- src/store/modules/trace/index.ts
- src/views/components/trace/trace-search.vue
Fixes https://github.com/apache/skywalking-rocketbot-ui/issues/356
Fixes browser dashboard selectors
Screenshot
when select "all" again in the service dropdown after selecting any service,  no instances in the instance dropdown
> fix: trace instance selector

- src/components/rk-footer.vue
- src/views/components/topology/topo-services.vue
Fixes the utc value in the footer and sort group names in the topology.
Screenshots
Enter the dashboard without utc local storage
> fix: update utc and sort group

- src/views/components/profile/task-list.vue
Use icons to replace buttons for task list in profile.
Optimization page style.
Screenshot
Signed-off-by Qiuxia Fan <qiuxiafan@apache.org>
> fix: use icons to replace buttons for task list in profile

- src/views/components/trace/trace-search.vue
- src/views/containers/topology/trace/index.vue
- src/views/containers/trace.vue
Use first = to separate key and value for tags in trace. Fix https://github.com/apache/skywalking/issues/6160
Screenshot
> fix: support `=` in the tag value in the trace query page.

- src/views/containers/topology/endpoint/endpoints-survey.vue
- src/views/containers/topology/instance/instances-survey.vue
`DashboardItem.vue` miss prop rocketOption :
- `endpoints-survey.vue` 
- `instances-survey.vue`
> DashboardItem miss prop `rocketOption`

- src/assets/lang/en.ts
- src/assets/lang/zh.ts
- src/graph/fragments/log.ts
- src/views/components/log/log-bar.vue
- src/views/components/log/log-conditions.vue
- src/views/components/log/log-table/log-constant.ts
- src/views/components/log/log-table/log-service-item.vue
- src/views/components/log/log-table/log-table.vue
- src/views/components/trace/trace-search.vue
Update query conditions for logs.
Reference https://github.com/apache/skywalking/issues/6276
> fix: update query conditions for logs

- src/store/modules/log/index.ts
- src/views/components/log/log-conditions.vue
Fixes https://github.com/apache/skywalking/issues/6429. Clear trace id by clear search conditions
Screenshots
The following image is search logs by trace id.
The following image is clear all of conditions, including trace id.
> fix: clear trace id by clear search conditions

- src/views/components/topology/topo-aside.vue
> When the topology radiation chart is displayed, the corresponding button should be highlighted.

- src/assets/lang/en.ts
- src/assets/lang/zh.ts
- src/views/components/dashboard/charts/chart-edit.vue
- src/views/components/dashboard/charts/chart-table.vue
- src/views/components/dashboard/dashboard-comp.vue
- src/views/components/dashboard/dashboard-item.vue
Extends table chart, including style, zoom width, add config, and copy data.
Screenshots
> feat: extend table chart

- src/views/components/dashboard/dashboard-item.vue
This is a simple enhancement to support a tooltip in the UI template.
> Add tooltip for dashboard component

- src/views/components/dashboard/charts/chart-edit.vue
- src/views/components/dashboard/charts/constant.ts
- src/views/components/trace/trace-search.vue
Fixes configuration type in dashboard. Reference https://github.com/apache/skywalking/issues/6878
Test
`
[{"name":"APM","type":"service","children":[{"name":"Global","children":[{"width":"3","title":"Services Load","height":"300","entityType":"Service","independentSelector":false,"metricType":"REGULAR_VALUE","metricName":"service_cpm","queryMetricType":"sortMetrics","chartType":"ChartSlow","parentService":false,"unit":"CPM - calls per minute","maxItemNum":"10","sortOrder":"DES","aggregation":"+"},{"width":3,"title":"Slow Services","height":"300","entityType":"Service","independentSelector":false,"metricType":"REGULAR_VALUE","metricName":"service_resp_time","queryMetricType":"sortMetrics","chartType":"ChartSlow","parentService":false,"unit":"ms","maxItemNum":"10","sortOrder":"DES"},{"width" …
> fix: update independentSelector in dashboard

- src/views/components/dashboard/charts/chart-edit.vue
- src/views/components/dashboard/charts/constant.ts
From @wankai123, remove the no use maxItemNum. 
After fixing
> fix: remove the no use maxItemNum for labeled-value metric, etc

- src/views/components/topology/topo-group/index.vue
- src/views/components/topology/topo-services.vue
Add a filter for serviceIds in services topology.
Screenshot
> fix: add a filter for serviceIds in services topology

- src/components/rk-date.vue
#508 
The display is still incomplete in Chinese
- zh
😖
- en
-----
I suggest removing ```left: - 80px;```, why ```-80px?``` here, If delete it, It can be displayed normally in multiple languages
- zh
- en
> fix: update the date component css
