src/components/rk-select.vue

rk-select.vue bugfix

---

src/store/modules/dashboard-endpoint.ts

code defect for null value

---

README.md

related issue: https://github.com/TinyAllen/rocketbot/issues/65

remove "Replace default UI" section.

---

src/store/modules/dashboard-endpoint.ts
src/store/modules/dashboard-instance.ts

Fixed showing previous item when select list is empty

---

Dockerfile
Dockerfile-ci
README.md

related issue: https://github.com/TinyAllen/rocketbot/issues/74

add faq section.

---

README.md

Add build.

---

package.json
src/components/index.ts
src/components/noty/bootstrap-v4.css
src/components/noty/index.ts
src/components/noty/noty.css
src/views/components/alarm/alarm-tool.vue
src/views/components/dashboard/charts/chart-slow.vue
src/views/components/dashboard/charts/chart-through.vue
src/views/components/dashboard/charts/chart-trace-db.vue
src/views/components/dashboard/charts/chart-trace.vue
src/views/components/dashboard/dashboard-comp.vue
src/views/components/topology/topo.vue
src/views/components/trace/trace-detail-chart-tree.vue
src/views/components/trace/trace-search.vue
src/views/components/trace/trace-table.vue
src/views/containers/alarm.vue
src/views/containers/dashboard.vue

1. fix Two issues in Trace page UI  bug.
2. fix issues in alarm page.
3. fix Tree mode height is not self-adaption UI  bug.
4. add tips when copy trace id and sql statement.
5. Topology line metric Detect Point can selected automatically.

Update: Fix bug

---

src/views/components/trace/d3-trace.js
src/views/components/trace/trace-detail-chart-list.vue

Only expand/collapse span nodes without showing its detail. #89

---

README.md

Remove Docker FAQ

---

src/utils/tooltip.scss
src/views/components/dashboard/tool-bar-select-endpoint-opt.vue
src/views/components/dashboard/tool-bar-select-endpoint.vue
vue.config.js

Fix https://github.com/apache/skywalking-rocketbot-ui/issues/104

Fix bug#104

---

src/graph/fragments/topology.ts
src/graph/query/topology.ts
src/store/modules/dashboard-endpoint.ts
src/store/modules/topo.ts
src/store/mutation-types.ts
src/views/components/topology/topo-aside.vue
src/views/components/topology/topo-select.vue
src/views/components/topology/topo-services.vue
src/views/components/topology/topo.vue

1. support topo serivce query.
2. support New topology query protocol#12
3. fix bug IDs can't be null#2704

Update: update topology

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/components/rk-footer.vue
src/components/rk-header.vue
src/store/modules/index.ts
src/store/mutation-types.ts
src/views/components/topology/topo.vue
src/views/components/trace/trace-detail.vue
src/views/components/trace/trace-search.vue
src/views/components/trace/trace-table.vue

1. UTC change from '-12 ~ +12' to '-12 ~ +14'.
2. Change global duration.
3. Change topology SLA threshold (99.99% => 98%).
**!!!**  Need a careful recheck all the charts, I'm afraid there will be duration mistakes that I overlook.

Update: update utc & duration

---

src/components/rk-header.vue

ref:
https://github.com/apache/skywalking/pull/2912

remove logout

---

README.md
src/views/components/topology/topo.vue

1 remove README.md login desc
2 fix node name indentation at topo page bug
before
after

Fix some issue

---

src/store/modules/dashboard/source/database.ts

fix bug: https://github.com/apache/skywalking/issues/2998

Fix: fix database sla and response bug

---

src/store/modules/dashboard/modules/dashboard-data.ts
src/store/modules/dashboard/modules/dashboard-option.ts
src/store/modules/dashboard/source/endpoint.ts
src/store/modules/dashboard/template/endpoint-template.ts
src/views/components/dashboard/charts/chart-trace.vue
src/views/components/dashboard/tool-bar-select-endpoint.vue
src/views/components/dashboard/tool-bar.vue
src/views/components/dashboard/tool-group.vue
src/views/containers/dashboard.vue
vue.config.js

Fix bug: 
- https://github.com/apache/skywalking/issues/3012
- https://github.com/apache/skywalking/issues/3009
- https://github.com/apache/skywalking/issues/2993
- https://github.com/apache/skywalking/issues/2850

Fix ui bug

---

src/views/components/trace/trace-chart-table/trace-container.vue
src/views/components/trace/trace-chart-table/trace-item.vue
src/views/components/trace/trace-chart-table/trace.scss
src/views/components/trace/trace-detail-chart-table.vue

Fix license issue. @kezhenxu94 We need to enhance UI CI. This header license issues happen multiple times.

Add license.

---

src/components/rk-date-calendar.vue

fix rk-date-calendar.vue error "TypeError: handler.apply is not a function"
* error screen capture:
* err info:
```js
vue.runtime.esm.js?2b0e:619
[Vue warn]: Error in v-on handler: "TypeError: handler.apply is not a function"
found in
---> <VueDatepickerLocalCalendar> at src/components/rk-date-calendar.vue
<VueDatepickerLocal> at src/components/rk-date.vue
<Footer> at src/components/rk-footer.vue
<RouterIndex> at src/views/containers/index.vue
<App> at src/App.vue
<Root>
vue.runtime.esm.js?2b0e:1887
TypeError: handler.apply is not a function
at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
at SVGSVGElement.invoker (vue.runtime.esm.js?2b0e:2178)
at SVGSVGElement.original._wrapper (vue.runtime.esm.js?2b0e:6876)
fix rk-date-calendar.vue error "TypeError: handler.apply is not a …
```

fix rk-date-calendar.vue error "TypeError: handler.apply is not a function"

---

src/utils/comparison.ts
src/views/components/topology/topo-services.vue

fix "The "topo-services" component did not update the data in time after modifying the time range on the topology page."

fix "The "topo-services" component did not update the data in time after modifying the time range on the topology page."

---

src/store/modules/trace/index.ts
src/store/mutation-types.ts
src/views/components/trace/d3-trace.js
src/views/components/trace/trace-detail-chart-list.vue
src/views/components/trace/trace-detail-chart-table.vue
src/views/components/trace/trace-search.vue
src/views/components/trace/trace-table.vue

1,  highlight selected trace item
2, add action to set default empty trace
3, add loading on trace-table and trace detail page 【table and list 】

Trace detail optimize

---

src/store/modules/dashboard/template/endpoint-template.ts

Fix chart unit error: https://github.com/apache/skywalking-rocketbot-ui/issues/136

Fix dashboard Endpoint Slow charts.

---

src/views/components/trace/d3-trace-tree.js
src/views/components/trace/trace-detail-chart-list.vue
src/views/components/trace/trace-detail-chart-table.vue
src/views/components/trace/trace-detail-chart-tree.vue

1. Fix language chinese => english.
2. fix span error status display.

Fix language chinese & span error status

---

src/views/components/alarm/alarm-select.vue
src/views/components/dashboard/charts/chart-bar.vue
src/views/components/dashboard/charts/chart-brief.vue
src/views/components/dashboard/charts/chart-count.vue
src/views/components/dashboard/charts/chart-edit.vue
src/views/components/dashboard/charts/chart-heap.vue
src/views/components/dashboard/charts/chart-heatmap.vue
src/views/components/dashboard/charts/chart-instance.vue
src/views/components/dashboard/charts/chart-line.vue
src/views/components/dashboard/charts/chart-num.vue
src/views/components/dashboard/charts/chart-sankey.vue
src/views/components/dashboard/charts/chart-slow.vue
src/views/components/dashboard/charts/chart-trace.vue
src/views/components/dashboard/dashboard-comp.vue
src/views/components/dashboard/dashboard-item.vue
src/views/components/dashboard/tool-bar-endpoint-select-opt.vue
src/views/components/dashboard/tool-bar-endpoint-select.vue
src/views/components/dashboard/tool-bar.vue
src/views/components/topology/topo-aside.vue
src/views/components/topology/topo-response.vue
src/views/components/topology/topo-select.vue
src/views/components/topology/topo-services.vue
src/views/components/trace/trace-detail.vue
src/views/components/trace/trace-search.vue
src/views/components/trace/trace-table.vue

The original component name confused me when developing, so I fixed it.

fix component name

---

.gitignore
package-lock.json
package.json
src/store/modules/topology/index.ts
src/views/components/topology/topo-aside.vue

add topo metrice chart zoom

---

src/components/rk-footer.vue
src/components/rk-header.vue

Fix auto refresh time range failure

Fix auto refresh time range failure

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/views/components/trace/d3-trace.js
src/views/components/trace/trace-detail-chart-list.vue

Support the trace list  display export png

add feature apache/skywaking#96

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/views/components/trace/trace-detail-chart-list.vue
src/views/components/trace/trace-search.vue

1. Fix International Language.
2. Optimize code structure.
3. Fix illegal code.
4. UI style change.

Fix bug && Optimize code structure

---

src/store/modules/dashboard/modules/dashboard-data-query.ts
src/store/modules/dashboard/source/endpoint.ts
src/store/modules/dashboard/source/index.ts
src/views/components/dashboard/charts/chart-count.vue
src/views/components/dashboard/charts/chart-sankey.vue

When query endpointTopology return .
Use `org.apache.skywalking.oap.query.graphql.resolver.MetadataQuery#getEndpointInfo` query EndpointInfo by endpointId ,then add EndpointInfo.serviceName to the node.value for display.

fix issue apache/skywalking#3588 .

---

src/views/components/trace/trace-detail-chart-list.vue

fix ci warring Exceeds maximum line length of 120

---

src/graph/fragments/option.ts

fix not show instance language
issue:

fix not show instance language

---

src/main.ts

The language may not initial when we first enter the system.
after fixed

Fix bug: language initialization failed

---

src/components/rk-footer-time.vue
src/components/rk-footer.vue
src/store/modules/global/index.ts

Fix bug: time select operation not in effect

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/components/rk-header.vue
src/views/components/trace/trace-search.vue

feature: add auto refresh time

---

src/components/rk-date.vue

Fix issue：https://github.com/apache/skywalking/issues/3791

Fix: fix date-components utc bug

---

src/assets/svg/honeycomb-selector.svg

fix: header

---

src/components/rk-popper.vue

This is the popper component，the base component for other components.

Component: popper component

---

src/views/components/dashboard/charts/chart-line.vue
src/views/components/topology/topo-response.vue

Feat: update percentile chart style

---

src/views/components/topology/topo-aside.vue
src/views/components/topology/topo-chart.vue

The PR update charts style in topo page, charts are clearer.

Feat: update topo chart

---

src/store/modules/comparison/comparison-store.ts
src/store/modules/dashboard/fragments/service.ts
src/store/modules/dashboard/source/index.ts
src/store/modules/dashboard/source/service.ts
src/store/modules/dashboard/template/service-template.ts
src/utils/queryChartData.ts
src/views/components/dashboard/charts/chart-num.vue
src/views/components/dashboard/dashboard-comp.vue
vue.config.js

Add Apdex Score for Service metrics and default layout of service level.

Feat: Add Apdex metric

---

package.json
src/App.vue
src/components/rk-back.vue
src/components/rk-button.vue
src/components/rk-footer.vue
src/main.ts
src/router.ts
src/shims-tsx.d.ts
src/store/index.ts
src/store/modules/topology/index.ts
src/views/components/alarm/alarm-tool.vue
src/views/components/dashboard/dashboard-comp.vue
src/views/components/dashboard/tool-bar.vue
src/views/components/topology/radial.vue
src/views/components/topology/topo-aside.vue
src/views/components/topology/topo-chart.vue
src/views/components/topology/topo-response.vue
src/views/components/topology/topo.vue
src/views/components/trace/trace-search.vue
src/views/containers/alarm.vue
src/views/containers/dashboard.vue
src/views/containers/endpoint-survey-window.vue
src/views/containers/instances-survey-window.vue
src/views/containers/topology.vue
src/views/containers/trace.vue

This reverts commit 08c7fb5e7c57c47a436ec568ee41ec04c3fc6b5d.

Revert "Feat: remove element-ui (#218)"

---

src/main.ts
src/utils/localtime.ts
src/views/components/dashboard/dashboard-comp.vue
src/views/components/topology/topo-aside.vue
src/views/components/topology/topo.vue

Enhanced topology left-click display service indicators

Enhanced topology left-click display service indicators

---

src/utils/localtime.ts
src/views/components/alarm/alarm-tool.vue
src/views/containers/alarm.vue

fix alarm unable to search

---

src/views/components/topology/topo-aside.vue

fix topo can't drag

---

src/views/components/topology/dependency-sankey.vue
src/views/components/topology/topo-detect-point.vue
src/views/components/topology/topo-instance-dependency.vue

fix: update drawer

---

src/graph/query/topology.ts
src/views/components/topology/topo-detect-point.vue

fix topo click node display redundant client and server element

fix topo click node display redundant client and server element

---

src/views/components/topology/topo-detect-point.vue

fix topo metric transformation

fix topo metric transformation

---

src/views/components/topology/topo-detect-point.vue

Fix add missing comma

---

src/store/modules/topology/index.ts
src/views/components/topology/chart-line.vue
src/views/components/topology/topo-instance-dependency.vue

Add a line chart instead old one

Fix line chart for instance dependency

---

src/graph/fragments/comparison.ts
src/graph/fragments/topology.ts
src/store/modules/comparison/comparison-const.ts
src/store/modules/comparison/comparison-store.ts
src/store/modules/dashboard/fragments/database.ts
src/store/modules/dashboard/fragments/endpoint.ts
src/store/modules/dashboard/fragments/global.ts
src/store/modules/dashboard/fragments/service.ts
src/store/modules/dashboard/source/database.ts
src/store/modules/dashboard/source/endpoint.ts
src/store/modules/dashboard/source/global.ts
src/store/modules/dashboard/source/service.ts
src/store/modules/topology/index.ts

Merge P50-99 into one metric.
reference  https://github.com/apache/skywalking/issues/4219
screenshots

Feat: merge P50-99 into percentile metric

---

src/components/rk-sidebox.vue
src/views/components/topology/chart-line.vue
src/views/components/topology/topo-chart.vue
src/views/components/topology/topo-detect-point.vue
src/views/components/topology/topo-instance-dependency.vue

Bug: Fix dependency display

---

src/views/components/topology/topo-chart.vue

Resolves https://github.com/apache/skywalking/issues/4273

fix Topology ui Service SLA show error

---

README.md

Indicate the release and contact channel more clear.

Add Contact channel and release description 

---

src/components/rk-sidebox.vue
src/views/containers/topology/topology.vue
src/views/containers/topology/trace/index.vue
src/views/containers/topology/trace/trace-search.vue
src/views/containers/topology/trace/trace-select.vue

1. fix topology trace detection service select error.
2. fix close button

Fix: Topology trace detection

---

src/store/modules/topology/index.ts

Fixed topology layout when the service has been changed.

Fix: Bug service-selection changing error

---

src/views/components/profile/profile-header.vue

Fix: init endpointName

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/components/rk-footer-time.vue
src/components/rk-footer.vue
src/utils/timeFormat.ts
src/views/components/trace/trace-search.vue
src/views/containers/topology/trace/trace-search.vue

Use `Day`  to instead `Month` when we use `graphql` to query data.
**screenshots**

Feat: time format month

---

src/views/components/common/trace-chart-table/trace-item.vue
src/views/components/common/trace-detail-chart-table.vue

Fixes trace table has one more column.
**screenshot**

bugfix: trace table

---

src/components/rk-page.vue
src/views/components/topology/topo-group/group-item.vue
src/views/components/topology/topo-group/index.vue

The service selections also have a 250px scroll bar

Feat: Update topology group pagement

---

src/views/components/common/trace-chart-table/trace-item.vue

Fixes type to view profile span

Fix: profile span

---

src/store/modules/dashboard/dashboard-option.ts
src/views/components/dashboard/dashboard-item.vue

Fix linkage of service/endpoint/instance selectors don't work.

Bugfix: dashboard common selectors

---

src/views/components/dashboard/dashboard-item.vue
src/views/containers/dashboard.vue

Fixes some special cases in dashboard
**screenshots**

Bugfix: Edit dashboard

---

src/views/components/dashboard/dashboard-item.vue
src/views/constant.ts
src/views/containers/dashboard.vue
src/views/containers/topology/endpoint/index.vue
src/views/containers/topology/instance/index.vue
src/views/containers/topology/topology.vue

Fixes https://github.com/apache/skywalking/issues/4877#issuecomment-641777993
Fixes re-render charts in instance and endpoint topology
Screenshot

Bugfix: service and instance in topology

---

src/views/components/common/trace-chart-table/trace-container.vue
src/views/components/common/trace-chart-table/trace-item.vue
src/views/components/common/trace-chart-table/trace.scss
src/views/components/common/trace-detail-chart-table.vue

Resolves https://github.com/apache/skywalking/issues/4550

Feat: add trace table scroll-x and method-th drag

---

src/views/components/common/trace-chart-table/trace.scss
src/views/components/profile/profile-container.vue
src/views/components/profile/profile-detail-chart-table.vue
src/views/components/profile/profile-item.vue
src/views/components/profile/profile.scss

Feat: update thread-stack

---

src/views/components/profile/profile-container.vue
src/views/components/profile/profile-item.vue
src/views/components/profile/profile.scss

Fix: profile display bug

---

src/store/modules/dashboard/dashboard-option.ts

Fixes database selector in dashboard

Bugfix: database param

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/views/components/dashboard/charts/chart-area.vue
src/views/components/dashboard/charts/chart-bar.vue
src/views/components/dashboard/charts/chart-edit.vue
src/views/components/dashboard/charts/chart-line.vue
src/views/components/dashboard/charts/constant.ts
src/views/components/dashboard/charts/index.ts

Reference https://github.com/apache/skywalking/issues/4906
**Screenshots**
Signed-off-by: Qiuxia Fan <fanqiuxia@apache.org>

Feat: Add chart options to components

---

src/views/components/common/trace-chart-table/trace-item.vue
src/views/components/profile/task-list.vue

Resolves https://github.com/apache/skywalking/issues/4861
Screenshots

Feat: Add status color in trace table

---

src/components/rk-echarts.vue
src/store/modules/topology/index.ts
src/views/components/dashboard/charts/chart-bar.vue
src/views/components/dashboard/charts/chart-line.vue
src/views/components/dashboard/tool-bar-endpoint-select.vue
src/views/containers/topology/endpoint-dependency/index.vue

Implement scrolling legends and tooltips  in graphics. Reference https://github.com/apache/skywalking/issues/5342
Screenshot
Singed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

Feat: implement scrolling legends and tooltips  in graphics

---

src/views/components/common/trace-detail-chart-table.vue
src/views/components/trace/trace-detail-chart-list.vue
src/views/components/trace/trace-detail-chart-tree.vue

issue: https://github.com/apache/skywalking/issues/5420

Feature: Add serviceCode in span detail

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/graph/fragments/option.ts

Fix https://github.com/apache/skywalking/issues/5852
Signed-off-by: Gao Hongtao <hanahmily@gmail.com>

Change "Service filter" to "Service group"

---

src/views/components/trace/trace-search.vue

Fix the local cache tag

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/graph/query/log.ts
src/graph/query/option.ts
src/views/components/dashboard/charts/chart-num.vue
src/views/components/dashboard/charts/chart-slow.vue
src/views/components/log/log-detail-table.vue
src/views/components/log/log-table/log-constant.ts
src/views/components/log/log-table/log-item.vue
src/views/components/log/log-table/log-table.vue
vue.config.js

Fixes https://github.com/apache/skywalking-rocketbot-ui/issues/381 and i18n console warnings
Optimize code
Screenshot

fix: dashboard metrics name and optimize code

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/components/rk-header.vue

Fixes https://github.com/apache/skywalking-rocketbot-ui/issues/380
Screenshot
When the time greater than 0, the reload function will be implemented. Add tips in UI.

fix: auto reload dashbaord

---

src/views/components/common/trace-chart-table/trace-item.vue
src/views/components/profile/profile-item.vue

Fixes https://github.com/apache/skywalking/issues/5918
Screenshot

Fix: Profile and Trace table style

---

src/views/components/dashboard/charts/chart-bar.vue
src/views/components/dashboard/charts/chart-line.vue

Fixes https://github.com/apache/skywalking-rocketbot-ui/issues/377
Screenshot

fix: chart tooltips style

---

src/views/components/topology/chart-line.vue
src/views/components/topology/topo-aside.vue
src/views/components/topology/topo-detect-point.vue
src/views/components/topology/topo-services.vue
src/views/containers/topology/topology.vue

Implement refreshing data for topology by updating date, including topology, metrics, services. Reference https://github.com/apache/skywalking-rocketbot-ui/issues/285
Screenshots
Singed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

feat: implement refreshing data for topology by updating date

---

src/graph/fragments/option.ts
src/views/components/topology/radial.vue
src/views/components/topology/topo-aside.vue
src/views/components/topology/topo-detect-point.vue
src/views/components/topology/topo-endpoint-dependency.vue
src/views/components/topology/topo-group/create-group.vue
src/views/components/topology/topo-group/group-item.vue
src/views/components/topology/topo-select.vue
src/views/components/topology/topo-services.vue

Implement group selector in the topology. Reference https://github.com/apache/skywalking/issues/5978
Fix metric name(Successful Rate (%))
Screenshots

Feat: Implement group selector in the topology

---

src/views/components/topology/topo-services.vue

Set all as default parameter for services selector
Screenshot

fix: set all as default parameter for services selector

---

src/views/components/topology/topo-services.vue

Fixes topology render all services nodes when changed groups
Screenshot

fix: render topology of all services

---

src/store/modules/dashboard/dashboard-data-query.ts
src/store/modules/dashboard/dashboard-option.ts
src/views/components/dashboard/dashboard-item.vue
src/views/components/topology/chart/topo.vue
src/views/components/topology/chart/utils/legend.js
src/views/components/topology/chart/utils/nodeElement.js
src/views/containers/dashboard.vue

Fix dashboard wrong instance. Add a legend for topology. Update the condition of error cube.
Screenshot
Visit this page for the first time

fix: update dashboard wrong instance and add a legend for topology

---

src/assets/lang/en.ts
src/components/rk-date-calendar.vue
src/components/rk-footer-time.vue
src/graph/query/dashboard.ts
src/graph/query/log.ts
src/graph/query/profile.ts
src/graph/query/topology.ts
src/views/components/topology/chart/topo.vue
src/views/components/trace/trace-search.vue

Update props of date component
Reference https://github.com/apache/skywalking/issues/4124#issuecomment-766469007
screenshot

fix: update props of date component

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/views/components/log/log-bar.vue
src/views/components/log/log-conditions.vue

Update search content for logs.
Screenshots

fix: update search content for logs

---

src/views/components/common/trace-select.vue
src/views/components/dashboard/tool-bar-endpoint-select.vue
src/views/components/dashboard/tool-bar-select.vue
src/views/components/log/log-bar.vue
src/views/components/log/log-table/log-service-item.vue
src/views/containers/topology/trace/trace-select.vue

Fixes search ui for logs. Update style of selectors to word wrap. Fixes logs time.
Reference https://github.com/apache/skywalking/issues/6294
Screenshots

fix: update ui for logs

---

src/assets/styles/reset.scss
src/components/rk-select.vue
src/views/components/alarm/alarm-select.vue
src/views/components/common/trace-select.vue
src/views/components/dashboard/tool-bar-endpoint-select.vue
src/views/components/dashboard/tool-bar-select.vue
src/views/components/profile/task-list.vue
src/views/components/topology/topo-select.vue
src/views/components/trace/trace-table.vue
src/views/containers/topology/trace/trace-select.vue

Update scroller to show. Reference https://github.com/apache/skywalking/issues/6317
Screenshots

fix: update scroller

---

src/store/modules/global/index.ts
src/utils/dateFormatStep.ts
src/views/components/log/log-bar.vue
src/views/components/log/log-conditions.vue
src/views/components/log/log-service-detail.vue
src/views/components/profile/profile-header.vue
src/views/components/trace/trace-search.vue

Implement searching logs with date. Reference https://github.com/apache/skywalking/issues/6343
Screenshots

feat: implement searching logs with date

---

src/store/modules/global/selectors.ts
src/views/components/dashboard/tool-bar-endpoint-select.vue
src/views/components/dashboard/tool-bar.vue
src/views/components/profile/profile-detail-chart-table.vue
src/views/containers/topology/instance/index.vue

Search endpoints with keywords. Reference https://github.com/apache/skywalking/issues/6444
Screenshot

feat: search endpoints with keywords

---

src/views/components/log/log-bar.vue

Fixes pageSize on logs page. Closes https://github.com/apache/skywalking-rocketbot-ui/issues/433
Screenshots
Signed-off-by Qiuxia Fan <qiuxiafan@apache.org>

fix: update pageSize on logs page

---

package-lock.json
package.json

Reference https://github.com/apache/skywalking-rocketbot-ui/issues/438

build: fix resolved url for vue-property-decorator

---

src/store/modules/topology/index.ts

Fixes instance dependency on the topo page.
ScreenShot

fix: update instance dependency

---

src/views/components/log/log-table/log-service-item.vue

Fix log pages tags column not updated

---

src/components/rk-footer.vue
src/views/components/topology/topo-group/index.vue

Fix the problem that the footer and topology group is shaded when the topology radiation is displayed.

---

src/components/rk-header.vue
src/views/components/common/trace-chart-table/trace-item.vue
src/views/components/common/trace-select.vue
src/views/components/dashboard/tool-bar/tool-bar.vue
src/views/components/log/log-bar.vue
src/views/components/log/log-conditions.vue
src/views/components/profile/profile-header.vue
src/views/components/profile/profile-task.vue
src/views/components/profile/profile-trace-detail.vue
src/views/components/profile/task-list.vue
src/views/components/topology/topo-detect-point.vue
src/views/components/topology/topo-instance-dependency.vue
src/views/components/trace/trace-detail.vue
src/views/components/trace/trace-search.vue
src/views/components/trace/trace-table.vue
src/views/containers/topology/endpoint-dependency/index.vue
src/views/containers/topology/endpoint/index.vue
src/views/containers/topology/instance/index.vue
src/views/containers/topology/trace/trace-select.vue
vue.config.js

variables that have been declared, no need to use `this` to point to in the template.

pref: remove the unnecessary `this`  in template.

---

src/views/components/topology/chart/topo.vue

Fix #453
Before fix:
After fix:

Topology optimization of two services that call each other. 

---

src/views/components/dashboard/charts/chart-table.vue
src/views/components/dashboard/dashboard-item.vue

Update table style.
Screenshot

fix: update table style

---

src/graph/fragments/trace.ts
src/views/components/trace/trace-span-logs.vue

Show instance name in the trace view.

---

src/views/components/dashboard/dashboard-item.vue

Fixes render multiple metrics in the dashboard.
Screenshot

fix: render multiple metrics in the dashboard

---

src/views/components/topology/topo-services.vue

Fixes groups in the topography.
Screenshots

fix: update groups

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/views/components/log/log-bar.vue
src/views/components/log/log-browser-detail.vue
src/views/components/log/log-content.vue
src/views/components/log/log-table/log-browser-item.vue
src/views/components/log/log-table/log-constant.ts
src/views/components/log/log-table/log-service-item.vue
src/views/components/log/log-table/log-table.vue

Refactor browser logs style and update js to ts.
Screenshot

refactor: update js to ts for browser logs and style change

---

src/components/rk-sidebox.vue
src/views/components/dashboard/dashboard-item.vue
src/views/components/dashboard/tool-bar/dashboard-events.vue
src/views/components/log/log-conditions.vue
src/views/components/topology/radial.vue
src/views/components/topology/topo-aside.vue
src/views/components/topology/topo-detect-point.vue
src/views/components/topology/topo-endpoint-dependency.vue
src/views/components/topology/topo-group/group-item.vue
src/views/components/topology/topo-group/index.vue
src/views/components/topology/topo-instance-dependency.vue
src/views/components/topology/topo-services.vue
src/views/components/trace/trace-table.vue
src/views/containers/topology/endpoint-dependency/index.vue

Fixes style of endpoint dependency. Reference https://github.com/apache/skywalking/issues/6787
Update Echarts config to v5.
Add new config to side box component.
Screenshot

fix: update style of endpoint dependency

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/views/components/dashboard/charts/chart-edit.vue
src/views/components/dashboard/dashboard-item.vue
src/views/components/trace/trace-search.vue
src/views/containers/dashboard.vue
vue.config.js

Reference https://github.com/apache/skywalking/issues/6791
Screenshots

feat: enhance the custom content of tooltips on dashboard

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/graph/fragments/alarm.ts
src/types/alarm.d.ts
src/views/components/alarm/alarm-table.vue
src/views/components/alarm/alarm-tool.vue
src/views/components/common/condition-tags.vue
src/views/components/common/index.ts
src/views/components/log/log-conditions.vue
src/views/components/log/log-service-detail.vue
src/views/components/trace/trace-search.vue

Reference https://github.com/apache/skywalking/issues/6821
Screenshot

feat: Support search and visualize alarms with tags

---

src/views/components/alarm/alarm-tool.vue
src/views/components/dashboard/charts/chart-edit.vue
src/views/components/dashboard/charts/constant.ts

There is a bug that the browser dashboard is unavailable on test env.
Meanwhile, refactor events for searching alarms to avoid multiple call the request.
Screenshots

fix: update configuration on dashboard

---

src/views/components/common/trace-chart-table/trace-container.vue

…so sorry, as the pictrue, I modify the judgment of the table head column,the column of 'Type' doesn't show the button

Fix a bug in the trace statistics page

---

src/views/components/common/trace-chart-table/trace-item.vue

Refer to https://github.com/apache/skywalking/issues/7060

fix: update component name for trace table

---

src/views/components/common/trace-chart-table/trace-item.vue

revert: update trace item

---

src/assets/lang/en.ts
src/assets/lang/zh.ts
src/graph/fragments/alarm.ts
src/types/alarm.d.ts
src/views/components/alarm/alarm-table.vue
src/views/components/alarm/constant.ts

Refer to https://github.com/apache/skywalking/issues/6889
Screenshots

Feat: visualize Events on the alarm page

---

.gitignore
src/utils/dateFormat.ts
src/views/components/alarm/alarm-tool.vue
src/views/components/log/log-conditions.vue
src/views/components/trace/trace-search.vue

Refer to https://github.com/apache/skywalking/issues/7045
Screenshots

fix: update duration step in graphs for trace and log

---

src/components/rk-date.vue
src/views/components/log/log-conditions.vue

Refer to https://github.com/apache/skywalking-rocketbot-ui/issues/493
Screenshot

fix: update the date component for log conditions

---

src/views/components/common/trace-select.vue
src/views/components/dashboard/tool-bar/tool-bar-endpoint-select.vue
src/views/components/dashboard/tool-bar/tool-bar-select.vue
src/views/components/topology/topo-select.vue

Fixes https://github.com/apache/skywalking/issues/7147#issuecomment-864915908
Screenshots

fix: update selector keys for duplicate options

---

src/views/components/common/trace-detail-chart-table.vue
src/views/components/profile/profile-trace-detail.vue
src/views/components/trace/trace-util.ts

Fixes https://github.com/apache/skywalking/issues/7184
Screenshots
Signed-off-by: Qiuxia Fan <Qiuxiafan@apache.org>

fix: update trace table

---

src/graph/fragments/topology.ts

 Fix the error of server response time in the topology.

---

src/views/components/dashboard/charts/chart-edit.vue

Fixes https://github.com/apache/skywalking/issues/7273
Screenshots

fix: set chart type

---

src/views/components/alarm/alarm-table.vue
src/views/components/common/index.scss
src/views/components/event/event-timeline.vue

Fixes style for event details.
Screenshot

fix: update style for event details

---

src/views/components/trace/trace-search.vue

Fixes https://github.com/apache/skywalking/pull/7444#issuecomment-896875703
Screenshot

fix: update endpointName to endpointId in the query trace condition

---

src/store/modules/global/selectors.ts
src/views/components/common/common-selector.vue
src/views/components/log/log-bar.vue

Fixes https://github.com/apache/skywalking/issues/7520
Screenshot

fix: search endpoints with keywords

---

src/store/modules/global/selectors.ts
src/views/components/common/common-selector.vue
src/views/components/log/log-bar.vue
src/views/components/trace/trace-search.vue

Search endpoints with keywords in the log bar.
Screenshots

fix: Search endpoints with keywords in the log bar

---

src/assets/lang/en.ts
src/store/modules/debug/log-lal.ts
src/views/components/debug/debug-constant.ts
src/views/components/debug/tool-bar.vue

Update debugger tool name.
Screenshot

fix: update debugger tool name

---

src/views/components/common/common-selector.vue

fix: In the trace panel, select service from the drop-down box, and click invalid when search

---

src/components/rk-alert.vue
src/graph/query/topology.ts
src/store/modules/topology/index.ts
src/views/components/common/alerts-content.vue

Fixes graph parameter of query for topology metrics.
Screenshots

fix: update graph parameter of query for topology metrics

---

src/store/modules/profile/profile-store.ts
src/store/modules/topology/index.ts
src/store/modules/trace/index.ts

Delete duplicate calls for endpoint dependency.
Update duplicate error names.
Screenshot

fix: delete duplicate calls for endpoint dependency

---

src/views/components/common/common-selector.vue
src/views/components/log/log-bar.vue
src/views/components/log/log-detail-content.vue

Optimize Log page style.
Screenshots

fix: optimize Log page style 

---

src/graph/fragments/dashboard.ts
src/graph/query/dashboard.ts
src/views/components/dashboard/charts/chart-edit.vue
src/views/components/dashboard/dashboard-item.vue

Avoid some abnormal settings for item config.

fix: avoid some abnormal settings

---

src/store/modules/global/selectors.ts

Fix query condition of events.

fix: query condition of events
